export const PAGE_FETCH_ERROR = 'PAGE_FETCH_ERROR';
export const PAGE_CIPHER_ERROR = 'PAGE_CIPHER_ERROR';
export const PAGE_DIGEST_MISMATCH_ERROR = 'PAGE_DIGEST_MISMATCH_ERROR';
export const MISSING_PASS_PHRASE_ERROR = 'MISSING_PASS_PHRASE_ERROR';