exports.PAGE_FETCH_ERROR = 'PAGE_FETCH_ERROR';
exports.PAGE_CIPHER_ERROR = 'PAGE_CIPHER_ERROR';
exports.PAGE_DIGEST_MISMATCH_ERROR = 'PAGE_DIGEST_MISMATCH_ERROR';
exports.MISSING_PASS_PHRASE_ERROR = 'MISSING_PASS_PHRASE_ERROR';